// Conteúdo informativo sobre PIX
export const pixInformation = {
  "pt-BR": {
    title: "Conheça o PIX",
    introduction: "O PIX revolucionou a forma como os brasileiros fazem transferências e pagamentos. Entenda melhor como funciona essa tecnologia e como você pode aproveitá-la ao máximo.",
    sections: [
      {
        title: "Como funciona o PIX?",
        content: "O PIX funciona 24 horas por dia, 7 dias por semana, inclusive em feriados. As transações são processadas em tempo real, levando apenas alguns segundos para serem concluídas. Diferente de outros métodos de transferência, o PIX não possui intermediários: o dinheiro sai diretamente da conta do pagador para a conta do recebedor.\n\nPara utilizar o PIX, você precisa cadastrar uma ou mais chaves em seu banco. As chaves podem ser seu CPF, CNPJ, e-mail, número de celular ou uma chave aleatória gerada pelo banco. Com a chave cadastrada, você poderá receber pagamentos de forma rápida e segura a qualquer momento.\n\nUm diferencial importante do PIX é que, para pessoas físicas e microempreendedores individuais, as transações são gratuitas, conforme determinação do Banco Central do Brasil."
      },
      {
        title: "Como gerar e usar QR Codes PIX?",
        content: "O QR Code PIX é uma forma visual de compartilhar suas informações de pagamento. Quando você gera um QR Code, ele contém todos os dados necessários para que alguém possa transferir dinheiro para você.\n\nAo utilizar nossa ferramenta, você pode gerar QR Codes PIX instantaneamente. Basta informar sua chave PIX (campo obrigatório) e, opcionalmente, adicionar um valor específico e uma descrição para identificação da transação.\n\nO QR Code gerado pode ser usado em diferentes situações:\n• Em seu estabelecimento comercial (impresso em placas ou exposto na tela)\n• Em seu site ou loja virtual\n• Em redes sociais e materiais de divulgação\n• Em notas fiscais e faturas\n• Para cobranças pessoais por mensagens"
      },
      {
        title: "Vantagens do QR Code PIX para negócios",
        content: "Implementar o QR Code PIX em seu negócio traz diversas vantagens:\n\n• Rapidez nas transações: receba pagamentos em segundos\n• Redução de custos: sem taxas para MEIs e tarifas menores para empresas\n• Facilidade para clientes: processo de pagamento simplificado\n• Disponibilidade constante: funciona 24/7, inclusive feriados\n• Segurança: transações protegidas pelo sistema bancário\n• Controle financeiro: identificação clara das transações com descrições\n\nPara maximizar essas vantagens, considere criar QR Codes específicos para diferentes produtos ou serviços, incluindo valores fixos e descrições detalhadas."
      },
      {
        title: "Tipos de QR Codes PIX",
        content: "Existem dois tipos principais de QR Codes PIX:\n\n• QR Code estático: ideal para uso contínuo, como em placas e materiais de divulgação. Pode ser gerado com ou sem valor definido.\n• QR Code dinâmico: gerado para uma transação específica, com validade limitada.\n\nCom nossa ferramenta, você pode criar QR Codes estáticos personalizados de acordo com suas necessidades. Inclua valores fixos para produtos de preço determinado ou deixe o valor em aberto para que o cliente preencha no momento do pagamento."
      },
      {
        title: "Dicas para usar QR Codes PIX eficientemente",
        content: "Para aproveitar ao máximo os QR Codes PIX:\n\n• Adicione uma descrição clara para facilitar a identificação da transação\n• Use valores pré-definidos para agilizar pagamentos de produtos específicos\n• Teste o QR Code antes de implementá-lo em grande escala\n• Imprima QR Codes em alta qualidade para garantir a leitura correta\n• Organize seus recebimentos usando descrições padronizadas para cada tipo de produto ou serviço\n\nLembre-se de que os QR Codes PIX são uma ferramenta poderosa para modernizar seu negócio e oferecer uma experiência de pagamento mais conveniente para seus clientes."
      }
    ]
  },
  "en": {
    title: "Understanding PIX",
    introduction: "PIX has revolutionized how Brazilians make transfers and payments. Learn more about how this technology works and how you can make the most of it.",
    sections: [
      {
        title: "How does PIX work?",
        content: "PIX works 24 hours a day, 7 days a week, including holidays. Transactions are processed in real-time, taking only seconds to complete. Unlike other transfer methods, PIX has no intermediaries: money goes directly from the payer's account to the receiver's account.\n\nTo use PIX, you need to register one or more keys with your bank. Keys can be your CPF (Brazilian ID), CNPJ (Brazilian Company ID), email, phone number, or a random key generated by the bank. With your key registered, you can receive payments quickly and securely at any time.\n\nAn important advantage of PIX is that, for individuals and individual microentrepreneurs, transactions are free of charge, as determined by the Central Bank of Brazil."
      },
      {
        title: "How to generate and use PIX QR Codes?",
        content: "PIX QR Code is a visual way to share your payment information. When you generate a QR Code, it contains all the necessary data for someone to transfer money to you.\n\nUsing our tool, you can generate PIX QR Codes instantly. Simply enter your PIX key (required field) and, optionally, add a specific amount and a description to identify the transaction.\n\nThe generated QR Code can be used in different situations:\n• In your business establishment (printed on signs or displayed on screen)\n• On your website or online store\n• On social media and promotional materials\n• On invoices and bills\n• For personal charges via messages"
      },
      {
        title: "Advantages of PIX QR Code for businesses",
        content: "Implementing PIX QR Code in your business brings several advantages:\n\n• Fast transactions: receive payments in seconds\n• Cost reduction: no fees for MEIs and lower fees for companies\n• Convenience for customers: simplified payment process\n• Constant availability: works 24/7, including holidays\n• Security: transactions protected by the banking system\n• Financial control: clear identification of transactions with descriptions\n\nTo maximize these advantages, consider creating specific QR Codes for different products or services, including fixed values and detailed descriptions."
      },
      {
        title: "Types of PIX QR Codes",
        content: "There are two main types of PIX QR Codes:\n\n• Static QR Code: ideal for continuous use, such as on signs and promotional materials. Can be generated with or without a defined value.\n• Dynamic QR Code: generated for a specific transaction, with limited validity.\n\nWith our tool, you can create custom static QR Codes according to your needs. Include fixed values for products with a determined price or leave the value open for the customer to fill in at the time of payment."
      },
      {
        title: "Tips for using PIX QR Codes efficiently",
        content: "To make the most of PIX QR Codes:\n\n• Add a clear description to facilitate transaction identification\n• Use predefined values to speed up payments for specific products\n• Test the QR Code before implementing it on a large scale\n• Print QR Codes in high quality to ensure correct reading\n• Organize your receipts using standardized descriptions for each type of product or service\n\nRemember that PIX QR Codes are a powerful tool to modernize your business and offer a more convenient payment experience for your customers."
      }
    ]
  }
};
